### ISSUE TITLE
Heartbeats support?

### ISSUE THREAD

**Issue by dg-eparizzi** [cloudamqp/amqp-client.js#31]
Does this library support heartbeats?

When I try to use heartbeat with this library (by appending `heartbeat=60` in the URL), I get an error and the client disconnects.

Client throws
```
connection closed by server 501 FRAME_ERROR - type 1, all octets = <<>>: unknown_frame 0 0
ERROR AMQPError: connection closed: FRAME_ERROR - type 1, all octets = <<>>: unknown_frame (501)
    at AMQPClient.parseFrames (file:///C:/Projects/amqp-client/node_modules/@cloudamqp/amqp-client/lib/mjs/amqp-base-client.js:256:49)
    at AMQPClient.onRead (file:///C:/Projects/amqp-client/node_modules/@cloudamqp/amqp-client/lib/mjs/amqp-socket-client.js:73:26)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Server logs shows:
```
2022-03-07 09:40:51.987000+00:00 [erro] <0.16753.3> Error on AMQP connection <0.16753.3> (172.22.0.6:60980 -> 172.22.0.5:5672, vhost: '/', user: 'consumer', state: running), channel 0:
2022-03-07 09:40:51.987000+00:00 [erro] <0.16753.3>  operation none caused a connection exception frame_error: "type 1, all octets = <<>>: unknown_frame"
2022-03-07 09:40:51.987000+00:00 [info] <0.16753.3> closing AMQP connection <0.16753.3> (172.22.0.6:60980 -> 172.22.0.5:5672, vhost: '/', user: 'consumer')
```

This works just fine using either the `amqp-node/amqplib` or `rascal` libraries.

**Comment by carlhoerberg** [comment]
Sorry about that, fixed
