### ISSUE TITLE
I got 4.1k ERR_STREAM_DESTROYED error when trying to call basicPublish, but the connection never closed

### ISSUE THREAD

**Issue by EverettSummer** [cloudamqp/amqp-client.js#38]
I use the amqp-client and try to reconnect whenever the connection is lost. when I got an error from basicPublish I will try to retry. before that, I will check the AMQPBaseClient.closed property. but it never changed to true.

Although now I know this error can happen and I can handle them manually. but it's better to indicate in document or have some logic to mark it as a socket error.

Here is the error object and call stack.
```
{
    "type": "Error",
    "message": "Cannot call write after a stream was destroyed",
    "stack": "Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed\n    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)\n    at new NodeError (node:internal/errors:372:5)\n    at _write (node:internal/streams/writable:322:11)\n    at TLSSocket.Writable.write (node:internal/streams/writable:335:10)\n    at <anonymous> (/app/node_modules/@cloudamqp/amqp-client/src/amqp-socket-client.ts:127:21)\n    at new Promise (<anonymous>)\n    at AMQPClient.send (/app/node_modules/@cloudamqp/amqp-client/src/amqp-socket-client.ts:125:12)\n    at AMQPChannel.basicPublish (/app/node_modules/@cloudamqp/amqp-client/src/amqp-channel.ts:345:29)\n    at AmqpClientJSImpl.publish (/services/AmqpClientJSImpl.ts:212:37)\n    at AmqpClientJSImpl.resendMessage (/services/AmqpClientJSImpl.ts:247:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "code": "ERR_STREAM_DESTROYED"
}
```

Stack:
```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at _write (node:internal/streams/writable:322:11)
    at TLSSocket.Writable.write (node:internal/streams/writable:335:10)
    at <anonymous> (/app/node_modules/@cloudamqp/amqp-client/src/amqp-socket-client.ts:127:21)
    at new Promise (<anonymous>)
    at AMQPClient.send (/app/node_modules/@cloudamqp/amqp-client/src/amqp-socket-client.ts:125:12)
    at AMQPChannel.basicPublish (/app/node_modules/@cloudamqp/amqp-client/src/amqp-channel.ts:345:29)
    at AmqpClientJSImpl.publish (/services/AmqpClientJSImpl.ts:212:37)
    at AmqpClientJSImpl.resendMessage (/services/AmqpClientJSImpl.ts:247:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

my code can be found here: https://github.com/irohalab/mira-shared/blob/c1a829540d6572b8b609216524205066e9d41d72/src/services/AmqpClientJSImpl.ts#L212

**Comment by carlhoerberg** [comment]
thank you for reporting, workin on a fix
